import logging

import requests
from django.db.models.signals import post_save
from django.http import HttpResponse
from django.urls import path
from django.core.exceptions import ValidationError

from plugin import InvenTreePlugin
from plugin.mixins import SettingsMixin, UrlsMixin

logger = logging.getLogger("inventree")


class ProductUrlPlugin(SettingsMixin, UrlsMixin, InvenTreePlugin):
    """Auto-populates a Part's external link with a public product URL,
    optionally creating a matching redirect in Shlink."""

    NAME = "ProductUrl"
    SLUG = "producturl"
    TITLE = "Product URL Generator"
    DESCRIPTION = "Automatically generates a public product page URL for parts"
    VERSION = "0.4.0"
    AUTHOR = "Fred Corp."

    SETTINGS = {
        "BASE_URL": {
            "name": "Base URL",
            "description": "Base URL prefix for generated product links (include trailing slash)",
            "default": "https://your.domain.com/",
        },
        "ID_SOURCE": {
            "name": "ID Source",
            "description": "Which part field to use as the identifier",
            "choices": [("pk", "Internal ID (PK)"), ("ipn", "IPN")],
            "default": "pk",
        },
        "ID_PADDING": {
            "name": "ID Zero-Padding",
            "description": "Zero-pad the numeric ID to this many digits (only applies when ID Source is PK)",
            "validator": int,
            "default": 8,
        },
        "OVERWRITE_EXISTING": {
            "name": "Overwrite Existing Links",
            "description": (
                "Only affects parts that already carry a link generated by this "
                "plugin (i.e. one starting with Base URL). Parts with a manually-set "
                "link or no link at all are always processed, regardless of this setting."
            ),
            "validator": bool,
            "default": False,
        },
        "SALEABLE_ONLY": {
            "name": "Saleable Parts Only",
            "description": "Only generate product URLs for parts marked as saleable",
            "validator": bool,
            "default": False,
        },
        "SET_AS_BARCODE": {
            "name": "Set URL as Barcode",
            "description": "Set the generated product URL as the part's barcode",
            "validator": bool,
            "default": False,
        },
        "SHLINK_ENABLED": {
            "name": "Enable Shlink Integration",
            "description": "Automatically create a matching redirect in Shlink for each generated URL",
            "validator": bool,
            "default": False,
        },
        "SHLINK_API_URL": {
            "name": "Shlink API URL",
            "description": "Base URL of your Shlink instance (e.g. https://product.fredcorp.cc)",
            "default": "",
        },
        "SHLINK_API_KEY": {
            "name": "Shlink API Key",
            "description": "API key generated in Shlink for this integration",
            "default": "",
            "protected": True,
        },
        "SHLINK_DEFAULT_LONG_URL": {
            "name": "Shlink Default Redirect",
            "description": "Fallback destination URL used when a part has no existing link set",
            "default": "",
        },
    }

    # --- shared helpers ---

    def _should_process(self, part):
        if self.get_setting("SALEABLE_ONLY") and not part.salable:
            return False
        return True

    def _get_identifier(self, part):
        source = self.get_setting("ID_SOURCE")
        if source == "ipn" and part.IPN:
            return part.IPN
        padding = self.get_setting("ID_PADDING")
        return str(part.pk).zfill(padding)

    def _is_own_generated_link(self, part):
        base_url = self.get_setting("BASE_URL")
        return bool(part.link) and part.link.startswith(base_url)

    def _create_shlink_redirect(self, slug, long_url):
        api_url = self.get_setting("SHLINK_API_URL").rstrip("/")
        api_key = self.get_setting("SHLINK_API_KEY")

        if not api_url or not api_key or not long_url:
            logger.warning(
                "ProductUrlPlugin: Shlink integration enabled but API URL, "
                "API key, or destination URL is missing - skipping redirect creation"
            )
            return

        try:
            response = requests.post(
                f"{api_url}/rest/v3/short-urls",
                headers={"X-Api-Key": api_key, "Content-Type": "application/json"},
                json={"customSlug": slug, "longUrl": long_url, "findIfExists": True},
                timeout=10,
            )
            response.raise_for_status()
        except requests.RequestException as e:
            logger.warning(
                f"ProductUrlPlugin: failed to create Shlink redirect for slug '{slug}': {e}"
            )

    def _generate_and_assign(self, part):
        base_url = self.get_setting("BASE_URL")
        identifier = self._get_identifier(part)
        short_url = f"{base_url}{identifier}"

        if self.get_setting("SHLINK_ENABLED"):
            existing_link = part.link
            if existing_link and not existing_link.startswith(base_url):
                long_url = existing_link
            else:
                long_url = self.get_setting("SHLINK_DEFAULT_LONG_URL")
            self._create_shlink_redirect(identifier, long_url)

        part.link = short_url

        if self.get_setting("SET_AS_BARCODE") and part.barcode_data != short_url:
            try:
                part.assign_barcode(barcode_data=short_url, save=False)
            except ValidationError as e:
                logger.warning(
                    f"ProductUrlPlugin: could not assign barcode for part {part.pk}: {e}"
                )

        part.save()

    def handle_part_created(self, part):
        """Entry point called from the post_save signal below."""
        if not self._should_process(part):
            return
        if self._is_own_generated_link(part) and not self.get_setting("OVERWRITE_EXISTING"):
            return
        self._generate_and_assign(part)

    # --- backfill endpoint (existing parts) ---

    def backfill_view(self, request):
        if not request.user.is_staff:
            return HttpResponse("Forbidden - staff access required", status=403)

        from part.models import Part

        base_url = self.get_setting("BASE_URL")
        overwrite = self.get_setting("OVERWRITE_EXISTING")

        qs = Part.objects.all() if overwrite else Part.objects.exclude(link__startswith=base_url)

        if self.get_setting("SALEABLE_ONLY"):
            qs = qs.filter(salable=True)

        updated = 0
        for part in qs:
            self._generate_and_assign(part)
            updated += 1

        return HttpResponse(
            f"Backfill complete: updated {updated} part(s). "
            f"<a href='/web/settings/admin/plugin/producturl/'>Back to plugin settings</a>"
        )

    def setup_urls(self):
        return [path("backfill/", self.backfill_view, name="backfill")]


# --- Django signal wiring ---
# InvenTree's EventMixin has no corresponding event for Part creation in this
# version (part/events.py defines no members), so we hook Django's own
# post_save signal directly instead. Using a string sender avoids importing
# the Part model at module-import time, which can happen before all Django
# apps are ready.

def _on_part_post_save(sender, instance, created, **kwargs):
    if not created:
        return

    from plugin.registry import registry

    plugin = registry.get_plugin("producturl")
    if plugin and plugin.is_active():
        plugin.handle_part_created(instance)


post_save.connect(
    _on_part_post_save,
    sender="part.Part",
    dispatch_uid="inventree_product_url_part_created",
    weak=False,
)
